version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: gtb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gtb_user
      - POSTGRES_PASSWORD=gtb_password
      - POSTGRES_DB=gtb_db
    ports:
      - "5432:5432"

  queue:
    image: redis:alpine
    container_name: gtb_queue
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: gtb_web
    command: python gestor_estoque/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Suestoque:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://gtb_user:gtb_password@db:5432/gtb_db
      - CELERY_BROKER_URL=redis://queue:6379/0
      - PYTHONPATH=/app
    depends_on:
      - db
      - queue

  worker:
    build: .
    container_name: gtb_worker
    command: /bin/bash /app/start_celery.sh
    volumes:
      - ./Suestoque:/app
      - ./start_celery.sh:/app/start_celery.sh
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://gtb_user:gtb_password@db:5432/gtb_db
      - CELERY_BROKER_URL=redis://queue:6379/0
      - PYTHONPATH=/app/gestor_estoque
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data: